### ISSUE TITLE
Adding custom OPD Number and Medicine dispensed

### ISSUE THREAD

**Issue by dantrolene** [informatici/openhospital#111]
Hi,
Is it possible to assign custom OPD numbers to the clients registered under OPD management and and column for details of medication dispensed to the clients in OPD?

Also how can I add more ICD 10 based diagnosis to the list of disorders? (I am looking to add Mental Health Related Disorders)

**Comment by mwithi** [comment]
Hi @dantrolene there are some developments on these regards that will be available by the next versions

For the OPD number you can just change it in the OPD No. field (must be an integer positive number)
![image](https://user-images.githubusercontent.com/2938553/82043879-9c5b6c80-96ac-11ea-9696-b64c6c6d65ee.png)

For the diagnosis you can add from GeneralData -> Diseases menu

Please refer to the UserGuide (HELP button) for more detailed explanations.

**Comment by dantrolene** [comment]
![Untitled](https://user-images.githubusercontent.com/7278230/82062831-53c1a480-96e8-11ea-85d3-58cefdc63489.png)
Hi,
I was trying to change the OH ID in this OPD registration to reflect the OPD Number. But it dies not happen. It reflects the number generated by OH.
Also can I request you to kindly add the "Others" option for patient sex in selection options?

**Comment by mwithi** [comment]
Hi,
that number "117" is the patient ID (that is automatic) actually the OPD number is not showed in that table, and the fact the patient ID starts from 117 is a minor bug that won't affect the functionalities. Created tickets OP-208 and OP-209

For the gender specification, we are working on the issue because we have to separate the concern between patient's privacy and medical informations, taking in account also different countries regulations. There was not a dedicated ticket for that but I've created right now OP-210.

Thanks very much for your suggestions!

**Comment by mwithi** [comment]
For ICD10 it will be distributed a subset with the next version 1.10

**Comment by dantrolene** [comment]
Thank you so much. I will be waiting for the next release.

**Comment by mwithi** [comment]
Both OP-208 and OP-209 has been done and will be available in the next version 1.10
