### ISSUE TITLE
OP-166 | Download MySQL during build process

### ISSUE THREAD

**Issue by pviotti** [informatici/openhospital#123]
As it's been done for JRE (#121) it'd be better to download MySQL during the build process.

**Comment by pviotti** [comment]
Question: can we upgrade to MySQL 5.6, since [OH-core is actually tested against that version](https://github.com/informatici/openhospital-core/blob/develop/Dockerfile-ohdb#L1)? Or even upgrade to 5.7 if all tests pass? cc: @mwithi

**Comment by mwithi** [comment]
Yes we can, we should also update the doc, as per OP-166

**Comment by mwithi** [comment]
OP-166 has been updated, should we consider to replace MySQL with MariaDB?

**Comment by emecas** [comment]
In order to make CORE works with MySQL 8, I had to make a couple changes. I can look for the specific details and provide them here, I barely remember a deprecated exception was involved and JDBC configuration. This could not be related to earlier versions of MySQL, just to make you aware while performing all testing against 5.7

Do you know about particular advantanges regarding to adopting MariaDB in OH or open source projects in general?

**Comment by mwithi** [comment]
> In order to make CORE works with MySQL 8, I had to make a couple changes. I can look for the specific details and provide them here, I barely remember a deprecated exception was involved and JDBC configuration. This could not be related to earlier versions of MySQL, just to make you aware while performing all testing against 5.7

We should consider what is currently supported in most OS, v5.7 could be already too old for most of them (Ubuntu 20.04 use v8.0.19)

> Do you know about particular advantanges regarding to adopting MariaDB in OH or open source projects in general?

just a [few](https://hackr.io/blog/mariadb-vs-mysql), but mostly because is "more opensource" even if not the most used, thus the most similar to one we are using. Nevertheless it could be too hard to do this switch at this stage and to embed the server part in the package during the release process (as it is now). 

Maybe we can do step by step, and first upgrade to MySQL 8. If it's still too much impacting, we can still consider 5.7 for the next release.

**Comment by pviotti** [comment]
I'd vote for MariaDB (even just for what the company that controls MySQL development did with [Java licenses](https://dev.karakun.com/java/2018/06/25/java-releases.html)).  
However, I was playing around with databases to fix https://github.com/informatici/openhospital-core/pull/120 and found that MariaDB has [its own JDBC connector library](https://mariadb.com/kb/en/about-mariadb-connector-j/), and despite claims of drop-in compatibility, there are [some differences](https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/).  
Also, it looks like the issues in https://github.com/informatici/openhospital-core/pull/120 are due to bugs with time zones and date time formats, which, IMO, we should understand and fix before migrating to other DBs.
