### ISSUE TITLE
Problem with Height (limited to 50cm) in Examination

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#54]
As per https://github.com/informatici/openhospital-doc/blob/master/doc_user/UserManual.adoc#10-admissionpatient-admissionpatient I sould be able to insert patien height in cm but current dialog has a limit of 50 units. Writing 174 in the box gets rounded to 50 as well

![Schermata 2020-02-11 alle 10 16 34](https://user-images.githubusercontent.com/1875906/74223735-a3db3600-4cb7-11ea-9f37-be9a2c99124f.png)

**Comment by mwithi** [comment]
The problem seems be affecting only the JSlider, but it is still possible to type and save higher values as specified in examination.properties ([doc](https://github.com/informatici/openhospital-doc/blob/master/doc_admin/AdminManual.adoc#5-4-examination-properties))

![image](https://user-images.githubusercontent.com/2938553/74525639-d25c4980-4f21-11ea-827f-ca101e281980.png)

Anyway this mask has been completely revised on branch [OP-171-VEZO_2-examination-window-changes](https://github.com/informatici/openhospital-gui/tree/OP-171-VEZO_2-examination-window-changes), task [OP-171](https://openhospital.atlassian.net/browse/OP-171) and will be available in the next release 1.10
