### ISSUE TITLE
Problem with dates in Operation data

### ISSUE THREAD

**Issue by virivigio** [informatici/openhospital#55]
As per https://github.com/informatici/openhospital-doc/blob/master/doc_user/UserManual.adoc#1053-insertmodify-surgery-data there are no specific requirements for an operation Date but, even setting TODAY, produces the attached message when global "save" is clicked. Individual "save" work smoothly. Nothing in the log.

![Schermata 2020-02-11 alle 10 52 11](https://user-images.githubusercontent.com/1875906/74226344-b146ef00-4cbc-11ea-9b55-777ba90f83a4.png)

**Comment by mwithi** [comment]
The problem comes only at the first saving of the admission data because the admission starting date is not yet set, so the saved operation date validation fails the comparison.

Quick (dirty) fix: to set the admission begin date on the admission object before the comparison
Complete fix: the comparison should be done in the validation method at manager level once the Admission object is passed for persistence, so the OperationRow object should be linked to the Admission entity with a One2many relation.

**Comment by mwithi** [comment]
Created issue on Jira **[OP-183](https://openhospital.atlassian.net/browse/OP-183)**

**Comment by mwithi** [comment]
Fixed with:
https://github.com/informatici/openhospital-core/pull/55
https://github.com/informatici/openhospital-gui/pull/68
https://github.com/informatici/openhospital-doc/pull/14
