### ISSUE TITLE
Proposal: Merge the repository into one.

### ISSUE THREAD

**Issue by larsgrefer** [informatici/openhospital#73]
I propose to merge the three repositories into one.

It seems to me, that the current structure with one "main" repo and three submodules is unnecessary complex.

**Comment by pviotti** [comment]
Personally I don't have experience about git subtrees, but from a quick search it does look as though they're better than submodules. Do you have any useful readings or personal experience about them to support this proposal? Specifically, what would change and what would improve with subtrees wrt modules?

**Comment by larsgrefer** [comment]
I'd propose to use neither subtrees nor submodules: Just use one git repository instead of four.
In my PR I just used `git subtree` to merge all the repositories together while keeping their histories.

If you follow my proposal, the repositories openhospital-core, -gui and -doc should be deleted/archived/made read-only after the merge has been done. From this point on,
all development should take place in this repository.

According to my experience, splitting a software across different git repositories isn't worth the overhead it produces.

**Comment by pviotti** [comment]
Oh, OK. I worked with larger "monorepos" in which the advantages of having the code base in a single location was actually dwarfed by issues related to code ownership, maintenance of common dependencies, CI/CD trouble, sheer size (wrt what can be managed by git), etc. I'm not saying this generalizes to these repositories, but it does hint to some limits.

In this specific case:
 1. your proposal and PR effectively undo the effort of splitting into modules OH, which we carried out about one year ago (the root work item was [OP-65](https://openhospital.atlassian.net/projects/OP/issues/?filter=allissues&orderby=priority%20DESC&keyword=split), I think) 
 2. I think it makes some sense to have separate projects AND separate repos for OH, since the projects are fairly different, maintained by different people (e.g. some are frontend engineers, some are just users that edit the [docs project](https://github.com/informatici/openhospital-doc), etc) which have different workflows and backgrounds. Also, this repository unfortunately has lots of binaries (because OH is currently distributed with full MySQL binaries..), and it would make all other projects heavier to clone and pull.

That said, I'm just a contributor to OH since about 1 ago (and FWIW I raised some of your same concerns when I joined - e.g. move to Maven standard structure). So I'll let @mwithi or other members with more historical perspective on the matter decide on this proposal. HTH

**Comment by larsgrefer** [comment]
@pviotti Thanks for sharing your thoughts. I'd like to add some more arguments based on this:

> maintenance of common dependencies

I think this is acutally easier in one multi-module project in one repository than in a project distributed across multiple repositories. In fact the current setup causes dependecy issues: https://openhospital.atlassian.net/projects/OP/issues/OP-178

> CI/CD trouble

Also for this point I think one multi-module project would be easier to build than the current distributed one.

> sheer size (wrt what can be managed by git)

I'd argue that openhospital will never (and should never) reach the size for this argument to become valid.

> 1. your proposal and PR effectively undo the effort of splitting into modules OH, which we carried out about one year ago

OP-65 seems to be only about splitting the project into different maven sub-projects, each producing its own jar file. I don't want to change this. openhospital should still consist of separate projects(jars). I only propose to keep all the (sub-)projects in the same git repository.

> 2. I think it makes some sense to have separate projects AND separate repos for OH, [...]

I see the point here. separate projects definitely make sense as I mentioned above. The slow initial clone is the only performance downside of git, but once the repository is initially cloned the pull performance should not be affected.

**Comment by mwithi** [comment]
Hi @larsgrefer and @pviotti, thanks very much for sharing your points of view. 

Paolo says the truth when it says that our initial effort has been specifically the one of separating different components, because each one will live different lifes.

It's not really a matter of "what is better" because all of us we come from different background and experiences, so everybody'd like to work with familiar tools and workflow (e.g. I always felt confortable with single-repository projects, but now I'm ok also with this setup).

Said so, I think we can HOLD on this, since we have other priorities in the project, well described by a number of [Jira issues](https://openhospital.atlassian.net/issues/?filter=10200), that in turn are also strictly relying on the multi-components setup.

One of this priority is to have the 1.9.1 (now in pre-release) up and running without problems. After that we will try to apply the mvn standard layout in the "core" and "gui" components, mind that it will not really affecting very much the functionalities but only the devs contributions, which is extremely important and we would do it specifically only for this purpose ;)

Concerning contributing: we had dependency issues because of this multi-components setup, someone already proposed to just organize the project with Maven modules, so not even having different repositories; but the upside of this structure is that, for instance, the frontend dev has not to clone one big repository with the whole stuff but only the components which is interested to work with. And also, this main parent repository was not meant for developing purpose, but just to package the releases. For the single dev, the suggested way is to clone each single repository. Can we live with it? :)

**Comment by larsgrefer** [comment]
My main goal with this is making contributing and fixing bugs easier

IMHO things like the over-complicated repository-structure, the non-standard directory layout (OP-181) etc. make the project harder to work with and therefore less attractive for new potential contributors.

**Comment by mwithi** [comment]
Yes @larsgrefer is what I'm also saying, the OP-181 will be done as soon as possible, but as for now would break the work that other devs is doing.

Nevertheless, this switch to git subtree (that I'm also trying to study) can be done at any time rather than the OP-181 one, because it doens't change the position of any code (unlike the OP-181 does), correct?

I beg some little patience. If you can help on the current bugs affecting 1.9.1 and 1.9.1-pre it would definetly boost the overall development.

**Comment by larsgrefer** [comment]
> Nevertheless, this switch to git subtree (that I'm also trying to study) can be done at any time rather than the OP-181 one, because it doens't change the position of any code (unlike the OP-181 does), correct?

In theory a switch to git subtree is possible at any time (all file paths would stay the same), but I'd like to emphasize that this was not my initial proposal. I just used git subtree for the merge.

If you wan't to keep the multi-repository solution (thus declining my initial proposal), replacing git submodule with git subtree is another option we could discuss.

**Comment by mwithi** [comment]
> I just used git subtree for the merge.
Yeah you're right

> replacing git submodule with git subtree is another option we could discuss.
This could be an option indeed, thus we have to understand if it really brings any benefit to the purpose of this repo

Thanks!

**Comment by b-abel** [comment]
Hi!
Here are the thoughts of someone who is new to the project and would like to contribute something. It takes me an unusually long time to orientate myself in this project. It would help if I could see at openhospital-core where the code is used (and if at all).
A Maven multi-module project ( I don't see the need for a monorepo that contains non-Java code) would certainly help and is currently pretty standard in the Java world from what I've observed.

**Comment by mwithi** [comment]
Hi @b-abel where do you see monorepo that contains non-Java code?

Concerning Maven modules, I quote myself above:
> Concerning contributing: we had dependency issues because of this multi-components setup, someone already proposed to just organize the project with Maven modules, so not even having different repositories; but the upside of this structure is that, for instance, the frontend dev has not to clone one big repository with the whole stuff but only the components which is interested to work with. And also, this main parent repository was not meant for developing purpose, but just to package the releases. For the single dev, the suggested way is to clone each single repository. Can we live with it? :)

**Comment by b-abel** [comment]
Hi @mwithi,

If the project does not consider the proposal to be helpful, I am fine with that. I certainly do not want to slow down development. 

> If you can help on the current bugs affecting 1.9.1 and 1.9.1-pre it would definetly boost the overall development.

Can you point me to where the help of new contributors would be most beneficial at the moment?

Just for reference: I solved my main problem (not seeing in OH-core where and if code is used) by adding OH-core, OG-gui and openhospital-api in IntelliJ IDEA as modules to one IntelliJ project (see: https://stackoverflow.com/a/31835633).

**Comment by mwithi** [comment]
@b-abel in the very shor term we are going to close the release 1.9.1 (now in pre-release) and among [other things](https://openhospital.atlassian.net/issues/?jql=project%20%3D%20OP%20AND%20fixVersion%20%3D%201.9.1) we need to verify if [OP-158](https://openhospital.atlassian.net/browse/OP-158) can be closed safely or not (means to test it and give a look at the code).
Otherwise all other [unresolved issues](https://openhospital.atlassian.net/issues/?filter=10200) on Jira are fine.

Thanks a lot!

**Comment by mwithi** [comment]
Closing this PR because it result clear to most that the proposal is denied at the moment, and also we are going to close GitHub issues for this repo (like the others).

Thanks a lot and see you on [Jira](https://openhospital.atlassian.net/jira/software/c/projects/OP/issues/?filter=allopenissues)!
