### ISSUE TITLE
Decide for one issue tracking system

### ISSUE THREAD

**Issue by larsgrefer** [informatici/openhospital#76]
At the moment both Jira and GitHub Issues seem to be used for issue tracking. This is confusing and redundant.

You should decide for one system and disable the other

I'd personally vote for using GitHub issues for better integration with PR's etc.

Some more thoughts about this can be found here (especially in the "Background" section): https://spring.io/blog/2019/01/15/spring-framework-s-migration-from-jira-to-github-issues

**Comment by mwithi** [comment]
Hi @larsgrefer, the Jira system is much powerful than GitHub's "Project" and it has been adopted before. The GitHub issues are **disabled** on the single components repositories, and are only enabled on this one, with the only purpose to collect tickets (unplanned issues/bugs) and the issues about the parent repository, while the Jira Ticketing system is meant to organise the whole project (planned issues) among all components.

We are not moving from Jira to GitHub at this stage. End users will use GitHub for ticketing (unplannned issues/bugs), the OpenHospital mantainers will convert them (if needed) into Jira issues in order to include them in the overall development.

We know about Jira Service Desk for end-users, but it's still very complex to setup and to use for an non-developers, but it would be the next-to-go solution rather than moving everything to GitHub.

I'm sorry for this lack of documentation and I hope will take change of these discussions to improve it.

@pviotti, do you think we can update the README in order to better explain the actual workflow for development and ticketing?

I'm sorry for this lack of documentation, I apologize for the confusion. Hope that these explanations can fit.

**Comment by larsgrefer** [comment]
A CONTRIBUTING file would be the way to go: https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

I think there should be CONTRIBUTING file for each repository

**Comment by mwithi** [comment]
We've just put everything in the README because lack of time since we work on a voluntary basis, but I totally agree with you @larsgrefer, don't you mind to help with this if you understood how the project is structured now?

**Comment by pviotti** [comment]
Yes, a CONTRIBUTING file would be the conventional way to encode these things. Happy to review any PR about it.

FWIW, as discussed several (too many :grinning:) times before, I agree with Lars on having all issues on GitHub, for mere practical convenience.

> Jira system is much powerful than GitHub's "Project"

True, I'm just not sure this project needs all that sophistication, to be honest - but I'm not a PM, nor the PM of this project, so I'll trust the PM on this :blush:

**Comment by mwithi** [comment]
> True, I'm just not sure this project needs all that sophistication, to be honest

It's an ambitious project... 😁

**Comment by emecas** [comment]
Regarding to this topic, and looking for some light  in order to put away some of the ambiguity 😁 .

I found this in confluence [Contribution Guidelines](https://openhospital.atlassian.net/wiki/spaces/OH/pages/6946820/Contribution+Guidelines) referencing JIRA usage, but also mentioning one more place called:  `community forums` : 

> Some important take-aways from the JIRA wiki:

>    1. Make sure it really is a bug - Questions are best handled in the community forums. If you are unsure if it's a bug, post in the forums and see if anyone else is having the same problem

 >   2. Provide as much detail as possible, including detailed steps on how to reproduce the bug. Also include a note outlining the intended results from performing the steps - How would it work if the bug did not exist?

 >   3. Search existing issues before posting a new one. The bug you encountered may have already been reported.

 Where are those `community forums` located?  or are those `community forums` right here, the issues on GitHub?  I did not find any particular link on https://www.informaticisenzafrontiere.org/ either

**Comment by mwithi** [comment]
hi @emecas thans for the question and to the typo in the Wiki. There is not a traditional forum website if it is what you was asking, maybe it was in plan by author @tommasomoroni, but now you get only the links in the [CONTRIBUTING.md](https://github.com/informatici/openhospital/blob/master/CONTRIBUTING.md) file created by @larsgrefer 🙏

we shall update that Wiki though...

**Comment by emecas** [comment]
> 
> hi @emecas thans for the question and to the typo in the Wiki. There is not a traditional forum website if it is what you was asking, maybe it was in plan by author @tommasomoroni, but now you get only the links in the [CONTRIBUTING.md](https://github.com/informatici/openhospital/blob/master/CONTRIBUTING.md) file created by @larsgrefer 🙏
> 

Thank you @mwithi 

Interesting, you have slack channel, email list, and  roadmap

I have joined the slack channel!  wonder if  that email list pretty active?

> we shall update that Wiki though...

Sure, even including the missing info. from CONTRIBUTING.md file there, I think it could be a good idea!

**Comment by mwithi** [comment]
@emecas yeah welcome over there! You can propose any change (means modify directly the Wiki, everything can be rolled-back in case), our first goal is to empower the Community. Welcome aboard!

**Comment by mwithi** [comment]
We are going to close GitHub Issues in favor of [Jira](https://openhospital.atlassian.net/jira/software/c/projects/OP/issues/?filter=allopenissues). See you there! Cheers!
